### ISSUE TITLE
请问能详细描述一下这个任务卸载场景吗？

### ISSUE THREAD

**Issue by little-boy-yah** [xuaikun/TransEdge#1]
代码中的device和server分别是指什么呢？以及为什么要使用PEMSD4这个数据集呢？

**Comment by xyrhahaha** [comment]
> 代码中的device和server分别是指什么呢？以及为什么要使用PEMSD4这个数据集呢？

想请问下 你能下载下来PEMSD04这个数据集嘛

**Comment by chenrui2200** [comment]
> PEMSD04
这里可以下载
https://www.kaggle.com/datasets/elmahy/pems-dataset/data

**Comment by chenrui2200** [comment]
device 看着像307个路口设备，但是真没懂action = np.random.choice(np.arange(n_servers), p=action_probs)  获取得动作表示什么？

**Comment by qing-2360629608** [comment]
> device 看着像307个路口设备，但是真没懂action = np.random.choice(np.arange(n_servers), p=action_probs) 获取得动作表示什么？

你好，我没找到的作者提供的TransEdge的代码，可以分享一下吗（qq2360629608）

**Comment by qing-2360629608** [comment]
> device 看着像307个路口设备，但是真没懂action = np.random.choice(np.arange(n_servers), p=action_probs) 获取得动作表示什么？

你好，我没找到作者提供的TransEdge的代码，可以分享一下吗（qq2360629608）
